# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'MeetupTech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for MeetupTech
	pod 'Alamofire', '~> 4.0'
	pod 'AlamofireImage', '~> 3.1'
	pod 'FontAwesomeKit/FontAwesome'
end
